### ISSUE TITLE
Test David's new segmenter params

### ISSUE THREAD

**Issue by pwoods25443** [SkyTruth/gpsdio-segment#41]
On this branch

https://github.com/SkyTruth/gpsdio-segment/tree/david-1

- I set max speed to 30 instead of 40. No boats really go above 20 that we care about.
 - For the reported speed, I ignored values 51.2 and 102.3, which are bad values. I also increased the reported speed by 10 percent to give a bit of a buffer.
 - I adjusted the above equation to
``` max_speed_at_distance = max_speed_at_inf * ((1 + 5/ (stats['distance'])**2) / 2) 
```

because it felt right. That plateaus at 20 minutes to the reasonable max speed (30 in my case).

**Comment by pwoods25443** [comment]
tweaked the params a bit to get the curve that we think we want.

**Comment by davidkroodsma** [comment]
![download-6](https://user-images.githubusercontent.com/3111114/31150414-52c64194-a848-11e7-941e-2b6a8706b009.png)

We may want to adjust this more...

**Comment by davidkroodsma** [comment]
![download-7](https://user-images.githubusercontent.com/3111114/31161677-884bb5ac-a88d-11e7-87b6-2d7f88fa3c06.png)

So, this is not useful segmenting.

**Comment by davidkroodsma** [comment]
![download-9](https://user-images.githubusercontent.com/3111114/31161792-6eb59968-a88e-11e7-920e-7fe77282f572.png)
version 0.8 is better.

**Comment by davidkroodsma** [comment]
![download-10](https://user-images.githubusercontent.com/3111114/31162222-e0065cd6-a890-11e7-8a7c-78556c9f3686.png)

In version 0.8 there are about 1/10th as many instances of this as in v 0.9_alpha, but it is still something we should try to avoid.

What is happening in this visualization is that there is a bad timestamp, and then points are added to the new segment, and then, as time goes on, eventually the new point matches back with the old segment and the new segment -- but because the old segment is longer, it gets matched back to the old segment. 

What we really want is to keep everything in the same segment, except for those jumps that we throw away.

Things like this show up in our current algorithm and map as "spoofing" and they shouldn't be.

**Comment by davidkroodsma** [comment]
@pwoods25443 So this is the situation that creates a problem:

 - a boat motors along, creating a long, normal segment.
 - a timestamp is off, so a new segment is created. the next few points match to the new segment.
 - eventually, as the new segment motors along, it matches back to the first segment _and_ the new segment, because you're averaging across more distance and time. Because the first segment is longer, the point gets added to the first, long segment
 - more points are added. An hour to a few hours later, a new point is wrong. That point doesn't meet the speed filter with the long segment, but because of the time and distance, it can be added to the shorter segment. What is interesting is that if you removed the most recent points from the long segment, it would also match to the long segment. *But* it doesn't match to the most recent point from the long segment. The result is the above blue and red points.

Ideally, what would happen is that the point a few hours later, that is outside the allowable range, is *not* added to the previous short segment. So, each of the blue dots on the above chart would be its own, isolated segment of only one to a few points. Then, you could simply ignore these short segments as noise that throws off our ability to track a vessel's movement. 

We could figure out how to adjust the code to do the above, but I think it is tricky based on our use of a speed cutoff. We'd have to do something that looks at the other recent segments, and if there is one that is out of range but within 100km and much longer than the segment it matches to, instead of matching, create a new segment. (That probably doesn't make sense -- I will have to explain). More likely, we should just have our segmenter focus on separating identity spoofing. A second segmenter could act on these tracks from specific vessels, using cutoff speeds tailored to the vessel and I am sure there are R packages for exactly this.

For us, I think we focus on keeping these points together with one vessel's voyage, even if they have really bad jumps on the scale of 10s of kilometers. Let's run the segmenter with the following 3 examples and inspect

 -  1. What we decided yesterday, using `max_speed_at_distance = max_speed_at_inf * (1 + 15 / (stats['distance'])**1.3)`
 -  2. a version that is much more permissive, which matches the v0.8 at for short distances, but then levels out to a more reasonable speed after an hour.  This equation: `max_speed_at_distance = 25 * ((1 + 40**2 / (distance**2)))` I have graphed this an the the others. Note how much stricter the version we agreed on yesterday is than the v.0.8 on the graph below, and the v0.8 did a better job of not getting as many overlaps of short segments like the graph above.
 - 3. a version that I'll commit shortly, that probably won't work

![download-11](https://user-images.githubusercontent.com/3111114/31189257-8ca87f68-a8ec-11e7-848f-365838660fba.png)

**Comment by davidkroodsma** [comment]
@pwoods25443 here's some ideas behind how to do the more complicated thing I suggested above... https://github.com/SkyTruth/gpsdio-segment/tree/david-overlap-test-fix

I'm would guess that this might cause more problems than it solves. But take a look at the logic (if it makes sense).

**Comment by pwoods25443** [comment]
Run some tests with these parameters  https://docs.google.com/spreadsheets/d/12os9qc0Eg--48XahytEotpJKwHdePxl-YmDMTcjcNZA/edit#gid=0

**Comment by pwoods25443** [comment]
Latest test runs

[`24---25---100---1-1---15---1-3`](https://console.cloud.google.com/dataflow/jobsDetail/locations/us-central1/jobs/2017-10-12_10_19_24-11851292852063023468?project=world-fishing-827)
[`24---25---100---1-1---1600---2-0`](https://console.cloud.google.com/dataflow/jobsDetail/locations/us-central1/jobs/2017-10-12_10_19_37-16172862904182960939?project=world-fishing-827)
